### ISSUE TITLE
unittest version

### ISSUE THREAD

**Issue by vicb** [GeReinhart/dart-gps-trace#2]
The unittest package use a semver versionning scheme then the version constraint shoulb probably be `unittest: ">=0.11.0+1 <0.12.0"`.

For example 0.11.0 (current version) is not BC with 0.8.0 (you min requirement)

**Comment by vicb** [comment]
Also your 0.1.1 is not BC with 0.1.0, this is bad and cause headaches for the user of your lib.

Semver says that:
- you should increment the minor version number on BC breaks pre 1.0.0
- then you should increment the major version number

**Comment by vicb** [comment]
> you should increment the minor version number on BC breaks pre 1.0.0

Actually this is not semver, this is the Dart usage of semver (semver is bad and wrong about that IMO)

**Comment by GeReinhart** [comment]
What do you mean by BC ? I should have increment to 0.2.0 ?

**Comment by vicb** [comment]
Backward compatibility

yes 0.2.0 should have been the way to go.

This because users will usually depends on ">=0.1.0 <0.2.0". 0.1.1 would break their application after a pub upgrade.

**Comment by vicb** [comment]
The proper way to fix this would be:
- To release a 0.1.2 which would remove the BC break,
- Release a 0.2.0 which re-include the BC break.

As the pkg is young, releasing 0.2.0 should be enough.

_We just had the same issue with the route pkg for angular.dart_

**Comment by GeReinhart** [comment]
thanks for the advise. will let it this way for now as nobody as use yet 0.1.0. 
will keep that in mind for next releases.

**Comment by vicb** [comment]
you should also update the readme to promote semver: 

```
dependencies:
  gps_trace: ">=0.m.p <0.m+1.0"
```
